/*
 * Giphy
 * Giphy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@giphy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.giphly.client.giphy.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * The Random ID Object contains a random hash.
 */
@Schema(description = "The Random ID Object contains a random hash. ")
@JsonPropertyOrder({ RandomId.JSON_PROPERTY_RANDOM_ID })
@javax.annotation.processing.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2020-02-10T13:51:22.963150-06:00[America/Chicago]"
)
public class RandomId {

    public static final String JSON_PROPERTY_RANDOM_ID = "random_id";
    private String randomId;

    public RandomId randomId(String randomId) {
        this.randomId = randomId;
        return this;
    }

    /**
     * Random ID hash used to associated with a user
     * @return randomId
     **/
    @javax.annotation.Nullable
    @Schema(example = "3640f6095c9a1f0f4e544b764d238b25", description = "Random ID hash used to associated with a user")
    @JsonProperty(JSON_PROPERTY_RANDOM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getRandomId() {
        return randomId;
    }

    public void setRandomId(String randomId) {
        this.randomId = randomId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RandomId randomId = (RandomId) o;
        return Objects.equals(this.randomId, randomId.randomId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(randomId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RandomId {\n");
        sb.append("    randomId: ").append(toIndentedString(randomId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
